export const resumeTips = [
    "Tailor your resume for each job application.",
    "Use a professional email address.",
    "Keep your resume to one page if you have less than 10 years of experience.",
    "Use bullet points to make your resume easy to read.",
    "Quantify your achievements with numbers and percentages.",
    "Start bullet points with strong action verbs.",
    "Avoid using personal pronouns like 'I' or 'me'.",
    "Proofread carefully for spelling and grammar errors.",
    "Use a clean, professional font like Arial, Calibri, or Helvetica.",
    "Include keywords from the job description.",
    "Focus on accomplishments, not just duties.",
    "Put your education section after your experience if you have work history.",
    "Include a skills section relevant to the job.",
    "Save your resume as a PDF to preserve formatting.",
    "Name your resume file professionally (e.g., FirstName_LastName_Resume.pdf).",
    "Include a link to your LinkedIn profile or portfolio.",
    "Don't list references on your resume; provide them when asked.",
    "Avoid using jargon or slang.",
    "Use consistent formatting for dates and headings.",
    "Highlight your most relevant experience first.",
    "Include volunteer work if it's relevant.",
    "Don't include personal information like age, marital status, or religion.",
    "Use reverse chronological order for your experience.",
    "Explain gaps in your employment history if necessary.",
    "Showcase your soft skills like communication and teamwork.",
    "Include certifications and awards.",
    "Customize your objective or summary statement.",
    "Use white space effectively to avoid clutter.",
    "Don't lie or exaggerate your qualifications.",
    "Get feedback from a mentor or friend.",
    "Use a consistent tense (usually past tense for past jobs).",
    "Focus on the last 10-15 years of experience.",
    "Include technical skills like software and languages.",
    "Use bolding or italics sparingly to emphasize key points.",
    "Don't include a photo unless it's standard in your industry/country.",
    "Check your contact information for accuracy.",
    "Use a font size between 10 and 12 points for body text.",
    "Make your headings distinct and easy to scan.",
    "Include your location (city and state is usually sufficient).",
    "Demonstrate problem-solving abilities.",
    "Highlight leadership experience.",
    "Showcase your ability to work under pressure.",
    "Include language proficiencies.",
    "Tailor your skills section to the specific job requirements.",
    "Avoid generic clichés like 'hard worker' without evidence.",
    "Use active voice.",
    "ensure your formatting is consistent throughout.",
    "Remove outdated or irrelevant experience.",
    "Highlight promotions or increased responsibilities.",
    "Showcase your adaptability and willingness to learn.",
    "Include relevant coursework if you're a recent graduate.",
    "Focus on results and impact.",
    "Use simple, clear language.",
    "Avoid large blocks of text.",
    "Make sure your resume is mobile-friendly.",
    "Test your resume with an ATS (Applicant Tracking System) scanner.",
    "Network to get your resume in front of a real person.",
    "Follow application instructions carefully.",
    "Use high-quality paper if printing your resume.",
    "Bring extra copies to your interview.",
    "Update your resume regularly.",
    "Keep a master resume with all your experience to pull from.",
    "Research the company culture before applying.",
    "Highlight experience with remote work tools if applicable.",
    "Showcase your ability to collaborate across teams.",
    "Include metrics like 'managed a budget of $50k'.",
    "Mention specific projects you've delivered.",
    "Highlight specialized training.",
    "Demonstrate functionality in high-stress environments.",
    "Showcase cross-functional communication skills.",
    "Limit formatting that confuses ATS (e.g., tables, graphics).",
    "Use simple headers.",
    "Include a 'Projects' section for technical roles.",
    "Mention open-source contributions if applicable.",
    "Link to your GitHub or GitLab profile.",
    "Highlight public speaking or presentation experience.",
    "Showcase mentoring or training experience.",
    "Include relevant hobbies only if they demonstrate transferable skills.",
    "Be concise.",
    "Use standard margins (usually 1 inch).",
    "Avoid using headers and footers for critical contact info (ATS might miss it).",
    "Include your phone number.",
    "Highlight efficiency improvements you implemented.",
    "Showcase revenue growth you contributed to.",
    "Mention cost-saving initiatives.",
    "Highlight successful client relationships.",
    "Demonstrate your ability to meet deadlines.",
    "Showcase time management skills.",
    "Include relevant keywords in your file name.",
    "Don't password protect your resume file.",
    "Avoid using 'Resume' as a header; your name should be the header.",
    "List your highest degree first.",
    "Include your GPA only if it's 3.5 or higher and you're a recent grad.",
    "Highlight honors and distinctions.",
    "Showcase study abroad experiences if relevant.",
    "Mention relevant professional memberships.",
    "Keep your formatting clean and modern.",
    "Be confident in your presentation.",
    "Let your personality shine through professionally."
];
